import { mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { resolve } from 'node:path';
import type { ResolvedOptions } from './options.js';

const PACKAGE_NAME = '@planttheidea/storybook-screenshot-tests';

/**
 * Files written beside the manifest so Playwright has something on disk to
 * point at. They live in the consuming application rather than in the package
 * because Playwright does not transform anything under `node_modules`, because
 * `globalSetup` and `reporter` are configured as paths rather than values, and
 * because this is where `@playwright/test` resolves to the runner's own copy —
 * the one whose registry it collects tests from.
 */
const GENERATED_FILES: Record<string, string> = {
  'run.screenshot.ts': `import { expect, test } from '@playwright/test';
import { registerScreenshotTests } from '${PACKAGE_NAME}';

registerScreenshotTests({ expect, test });
`,
  'global-setup.ts': `import { chromium } from '@playwright/test';
import { globalSetup } from '${PACKAGE_NAME}';

export default function setUpScreenshots() {
  return globalSetup(chromium);
}
`,
  'reporter.ts': `import { ScreenshotReporter } from '${PACKAGE_NAME}';

export default ScreenshotReporter;
`,
  '.gitignore': `*
`,
};

const HEADER = `// Generated by ${PACKAGE_NAME}. Do not edit.\n`;

/**
 * Writes the generated directory during config load — before Playwright
 * discovers test files, and before `globalSetup` runs.
 *
 * Writing these in `globalSetup` would be too late for `--list`, UI mode, and
 * the editor extensions, which load test files without running global setup.
 *
 * Files are only rewritten when their content changes, so an editor watching
 * the directory is not woken on every run.
 */
export function setGeneratedFiles(directory: string, options: ResolvedOptions): void {
  mkdirSync(directory, { recursive: true });

  for (const [fileName, body] of Object.entries(GENERATED_FILES)) {
    const content = fileName.endsWith('.ts') ? `${HEADER}${body}` : body;

    setFileWhenChanged(resolve(directory, fileName), content);
  }

  setFileWhenChanged(resolve(directory, 'options.json'), `${JSON.stringify(options, null, 2)}\n`);
}

function setFileWhenChanged(filePath: string, content: string): void {
  try {
    if (readFileSync(filePath, 'utf-8') === content) {
      return;
    }
  } catch {
    // Absent or unreadable; fall through and write it.
  }

  writeFileSync(filePath, content);
}
