import { mkdtempSync, readdirSync, readFileSync, rmSync, statSync, utimesSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { afterEach, beforeEach, describe, expect, it } from 'vitest';
import { setFileWhenChanged, setGeneratedFiles } from '../src/generateFiles.js';
import { resolveOptions } from '../src/options.js';

let root: string;

beforeEach(() => {
  root = mkdtempSync(join(tmpdir(), 'screenshot-generate-'));
});

afterEach(() => {
  rmSync(root, { recursive: true, force: true });
});

describe('setFileWhenChanged', () => {
  it('writes a file that does not exist yet', () => {
    const filePath = join(root, 'new.txt');

    setFileWhenChanged(filePath, 'content');

    expect(readFileSync(filePath, 'utf-8')).toBe('content');
  });

  it('rewrites a file whose content differs', () => {
    const filePath = join(root, 'changed.txt');

    writeFileSync(filePath, 'old');
    setFileWhenChanged(filePath, 'new');

    expect(readFileSync(filePath, 'utf-8')).toBe('new');
  });

  it('leaves a file with identical content untouched, so watchers are not woken', () => {
    const filePath = join(root, 'same.txt');
    const past = new Date('2020-01-01T00:00:00.000Z');

    writeFileSync(filePath, 'same');
    utimesSync(filePath, past, past);
    setFileWhenChanged(filePath, 'same');

    expect(statSync(filePath).mtime.getTime()).toBe(past.getTime());
  });
});

describe('setGeneratedFiles', () => {
  it('writes the stubs, the gitignore, and the resolved options', () => {
    const directory = join(root, 'generated');
    const options = resolveOptions({ projects: [{ name: 'light' }] }, root);

    setGeneratedFiles(directory, options);

    expect(readdirSync(directory).sort()).toEqual(
      ['.gitignore', 'global-setup.ts', 'options.json', 'reporter.ts', 'run.screenshot.ts'].sort(),
    );
    expect(JSON.parse(readFileSync(join(directory, 'options.json'), 'utf-8'))).toEqual(options);
  });

  it('marks the generated source files as generated', () => {
    const directory = join(root, 'generated');

    setGeneratedFiles(directory, resolveOptions({ projects: [{ name: 'light' }] }, root));

    expect(readFileSync(join(directory, 'global-setup.ts'), 'utf-8')).toMatch(/^\/\/ Generated by /);
    expect(readFileSync(join(directory, '.gitignore'), 'utf-8')).toBe('*\n');
  });
});
